package gengo

// 报错行号+3
const goCodeTemplate = `// Auto generated by github.com/davyxu/cellmesh/protogen
// DO NOT EDIT!

package {{.PackageName}}

import (	
	"github.com/davyxu/cellnet"	
)

// Make compiler import happy
var(
	_ cellnet.Event
)

{{range ServiceGroup $}}
// {{$svcName := .Key}}{{$svcName}}
var ( {{range .Group}}
	Handle_{{ExportSymbolName $svcName}}_{{.Name}} = func(ev cellnet.Event){ panic("'{{.Name}}' not handled") } {{end}}
	Handle_{{ExportSymbolName $svcName}}_Default func(ev cellnet.Event)
)
{{end}}

func GetMessageHandler(svcName string) cellnet.EventCallback {

	switch svcName { {{range ServiceGroup $}}
	case "{{$svcName := .Key}}{{$svcName}}":
		return func(ev cellnet.Event) {
			switch ev.Message().(type) { {{range .Group}}
			case *{{.Name}}:
				Handle_{{ExportSymbolName $svcName}}_{{.Name}}(ev) {{end}}
			default:
				if Handle_{{ExportSymbolName $svcName}}_Default != nil {
					Handle_{{ExportSymbolName $svcName}}_Default(ev)
				}
			}
		} {{end}}
	} 

	return nil
}
`
