// Auto generated by github.com/davyxu/cellmesh/protogen
// DO NOT EDIT!

package proto

import (
	"fmt"
	"reflect"
	"github.com/davyxu/cellnet"
	"github.com/davyxu/cellnet/codec"
	"github.com/davyxu/cellmesh/service"
	_ "github.com/davyxu/cellnet/codec/json"
)

// Make compiler import happy
var (
	_ service.Service
	_ cellnet.Peer
	_ cellnet.Codec
	_ reflect.Type
	_ fmt.Formatter
)

type ResultCode int32

const (
	ResultCode_NoError      ResultCode = 0
	ResultCode_GameNotReady ResultCode = 1
)

var (
	ResultCodeMapperValueByName = map[string]int32{
		"NoError":      0,
		"GameNotReady": 1,
	}

	ResultCodeMapperNameByValue = map[int32]string{
		0: "NoError",
		1: "GameNotReady",
	}

	ResultCodeMapperTrailingCommentByValue = map[int32]string{
		0: "",
		1: "",
	}
)

func (self ResultCode) String() string {
	return ResultCodeMapperNameByValue[int32(self)]
}

type ServerInfo struct {
	IP   string
	Port int32
}

type LoginREQ struct {
	Version  string
	Platform string
	UID      string
}

type LoginACK struct {
	Result    ResultCode
	Server    ServerInfo
	GameToken string
}

type VerifyREQ struct {
	GameToken string
}

type VerifyACK struct {
	Result ResultCode
}

type ChatREQ struct {
	Content string
}

type ChatACK struct {
	Content string
}

type ServiceIdentifyACK struct {
	SvcName string
	SvcID   string
}

type RouterBindUserACK struct {
	ID int64
}

type ClientClosedACK struct {
	ID int64
}

func (self *ServerInfo) String() string         { return fmt.Sprintf("%+v", *self) }
func (self *LoginREQ) String() string           { return fmt.Sprintf("%+v", *self) }
func (self *LoginACK) String() string           { return fmt.Sprintf("%+v", *self) }
func (self *VerifyREQ) String() string          { return fmt.Sprintf("%+v", *self) }
func (self *VerifyACK) String() string          { return fmt.Sprintf("%+v", *self) }
func (self *ChatREQ) String() string            { return fmt.Sprintf("%+v", *self) }
func (self *ChatACK) String() string            { return fmt.Sprintf("%+v", *self) }
func (self *ServiceIdentifyACK) String() string { return fmt.Sprintf("%+v", *self) }
func (self *RouterBindUserACK) String() string  { return fmt.Sprintf("%+v", *self) }
func (self *ClientClosedACK) String() string    { return fmt.Sprintf("%+v", *self) }

func GetRPCPair(req interface{}) reflect.Type {

	switch req.(type) {
	case *LoginREQ:
		return reflect.TypeOf((*LoginACK)(nil)).Elem()
	case *VerifyREQ:
		return reflect.TypeOf((*VerifyACK)(nil)).Elem()
	case *ChatREQ:
		return reflect.TypeOf((*ChatACK)(nil)).Elem()
	}

	return nil
}

// game
var (
	Handle_Game_ChatREQ   = func(ev service.Event, msg *ChatREQ) { panic("'ChatREQ' not handled") }
	Handle_Game_VerifyREQ = func(ev service.Event, msg *VerifyREQ) { panic("'VerifyREQ' not handled") }
	Handle_Game_Default   func(ev service.Event)
)

// login
var (
	Handle_Login_LoginREQ = func(ev service.Event, msg *LoginREQ) { panic("'LoginREQ' not handled") }
	Handle_Login_Default  func(ev service.Event)
)

// router
var (
	Handle_Router_RouterBindUserACK = func(ev service.Event, msg *RouterBindUserACK) { panic("'RouterBindUserACK' not handled") }
	Handle_Router_Default           func(ev service.Event)
)

func GetDispatcher(svcName string) service.DispatcherFunc {

	switch svcName {
	case "game":
		return func(ev service.Event) {
			switch req := ev.Message().(type) {
			case *ChatREQ:
				Handle_Game_ChatREQ(ev, req)
			case *VerifyREQ:
				Handle_Game_VerifyREQ(ev, req)
			default:
				if Handle_Game_Default != nil {
					Handle_Game_Default(ev)
				}
			}
		}
	case "login":
		return func(ev service.Event) {
			switch req := ev.Message().(type) {
			case *LoginREQ:
				Handle_Login_LoginREQ(ev, req)
			default:
				if Handle_Login_Default != nil {
					Handle_Login_Default(ev)
				}
			}
		}
	case "router":
		return func(ev service.Event) {
			switch req := ev.Message().(type) {
			case *RouterBindUserACK:
				Handle_Router_RouterBindUserACK(ev, req)
			default:
				if Handle_Router_Default != nil {
					Handle_Router_Default(ev)
				}
			}
		}
	}

	return nil
}

func init() {

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("json"),
		Type:  reflect.TypeOf((*LoginREQ)(nil)).Elem(),
		ID:    39009,
	})

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("json"),
		Type:  reflect.TypeOf((*LoginACK)(nil)).Elem(),
		ID:    840,
	})

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("binary"),
		Type:  reflect.TypeOf((*VerifyREQ)(nil)).Elem(),
		ID:    23773,
	})

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("binary"),
		Type:  reflect.TypeOf((*VerifyACK)(nil)).Elem(),
		ID:    51140,
	})

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("binary"),
		Type:  reflect.TypeOf((*ChatREQ)(nil)).Elem(),
		ID:    5832,
	})

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("binary"),
		Type:  reflect.TypeOf((*ChatACK)(nil)).Elem(),
		ID:    33199,
	})

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("binary"),
		Type:  reflect.TypeOf((*ServiceIdentifyACK)(nil)).Elem(),
		ID:    49180,
	})

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("binary"),
		Type:  reflect.TypeOf((*RouterBindUserACK)(nil)).Elem(),
		ID:    61868,
	})

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("binary"),
		Type:  reflect.TypeOf((*ClientClosedACK)(nil)).Elem(),
		ID:    63464,
	})

}
